import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'introduction/intro',
        'introduction/why-physical-ai-matters',
        'introduction/learning-outcomes',
      ],
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1-ros2/ros-architecture',
        'module-1-ros2/python-ros-bridge',
        'module-1-ros2/urdf-for-humanoids',
        'module-1-ros2/summary',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module-2-digital-twin/digital-twin-concept',
        'module-2-digital-twin/physics-simulation',
        'module-2-digital-twin/sensor-simulation',
        'module-2-digital-twin/unity-for-hri',
        'module-2-digital-twin/summary',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'module-3-nvidia-isaac/what-is-isaac',
        'module-3-nvidia-isaac/synthetic-data-perception',
        'module-3-nvidia-isaac/vslam-navigation',
        'module-3-nvidia-isaac/reinforcement-learning',
        'module-3-nvidia-isaac/sim-to-real',
        'module-3-nvidia-isaac/summary',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA) & Capstone',
      items: [
        'module-4-vla-capstone/voice-to-action',
        'module-4-vla-capstone/llm-planning',
        'module-4-vla-capstone/vla-loop',
        'module-4-vla-capstone/capstone',
        'module-4-vla-capstone/capstone-summary',
      ],
    },
    {
      type: 'category',
      label: 'Hardware & System Architecture',
      items: [
        'hardware/simulation-workstation',
        'hardware/edge-ai-kit',
        'hardware/robot-lab-options',
        'hardware/on-prem-vs-cloud',
      ],
    },
    {
      type: 'autogenerated',
      dirName: 'summary',
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
